### ISSUE TITLE
Bootstrap instructions not working

### ISSUE THREAD

**Issue by MartyLake** [AnotherKamila/tasksched#19] opened 2018-02-07 09:09 UTC
Hi !

Tried to start this project, but it seems that the bootstrap instructions are missing something:

```
$ sudo apt install vagrant virtualbox
... //install goes ok

$ vagrant up
Bringing machine 'tasksched' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* The following settings shouldn't exist: insert_key, password

vm:
* The box 'https://files.devuan.org/devuan_jessie/virtual/devuan_jessie_1.0.0_amd64_vagrant.box' could not be found.
```

**Comment by AnotherKamila** [comment] 2018-02-07 22:58
Hi,

I personally don't use the Vagrantfile, I think it's easier to install it on your host instead of running in a VM (assuming you are running linux). However, @evilham should be able to help.

Glad to see somebody is using this :-)

**Comment by evilham** [comment] 2018-02-07 23:07
:-D Apparently it's not `vm.box` but `vm.box_url`. For some reason it just worked for me.

Can you try the `19-evilham-vagrantfix` branch?
https://github.com/AnotherKamila/tasksched/tree/19-evilham-vagrantfix

**Comment by MartyLake** [comment] 2018-02-08 08:33
Thanks for the swift answer ! One of the error is gone, the other is still there:

```
~/tmp/tasksched$ git checkout 19-evilham-vagrantfix
// OK

~/tmp/tasksched$ vagrant up
Bringing machine 'tasksched' up with 'virtualbox' provider...
[tasksched] Box 'devuan' was not found. Fetching box from specified URL for
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading box from URL: https://files.devuan.org/devuan_jessie/virtual/devuan_jessie_1.0.0_amd64_vagrant.box
Extracting box...te: 7931k/s, Estimated time remaining: 0:00:01)
Successfully added box 'devuan' with provider 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* The following settings shouldn't exist: password
```

**Comment by evilham** [comment] 2018-02-08 11:39
That's a bit weird, it should be a valid setting according to the documentation:
https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

In any case, try the patched file and if asked for a password use `toor`.

**Comment by AnotherKamila** [comment] 2018-02-08 11:48
@evilham thanks for your help!

@MartyLake Just a note: using Vagrant for this is a bit of a special case, and not the recommended way to use (or develop!) this project. I have reworked the "how to use" section of the README, in case it was confusing -- see the new shiny https://github.com/AnotherKamila/tasksched/blob/master/README.md#how-to-use . Of course, if you do have a reason to use Vagrant, ignore me -- hopefully @evilham will be able to figure out the problem.

BTW, could your problem maybe be caused by having an old version of Vagrant? (I don't use it, just guessing.)

**Comment by evilham** [comment] 2018-02-08 13:07
Fair point :-D I thought that was clear, but it is much more so now ^^.

**Comment by evilham** [comment] 2018-02-16 15:15
Closing and merging, if there are still issues do re-open it :).

**Closed as completed by evilham** 2018-02-16 15:15 UTC
Labels: bug
